# Generated by Django 4.2.24 on 2025-09-25 22:15

import Aplicaciones.Medessentia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cedula_usuario',
            field=models.CharField(max_length=10, unique=True, validators=[Aplicaciones.Medessentia.models.validar_cedula_ecuatoriana]),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion_usuario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono_usuario',
            field=models.CharField(blank=True, default='0000000000', max_length=10),
        ),
    ]
