# Generated by Django 4.2.24 on 2025-09-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0002_alter_perfilusuario_cedula_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='glucosa_capilar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='hemoglobina',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='pa_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='pa_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='pa_sistolica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
