# Generated by Django 4.2.23 on 2025-10-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0003_signosvitales_glucosa_capilar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAtencion',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('peso_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField()),
            ],
            options={
                'db_table': 'archivo_atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoCita',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField()),
            ],
            options={
                'db_table': 'archivo_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionCie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIO', 'Secundario'), ('PRESUNTIVO', 'Presuntivo'), ('DEFINITIVO', 'Definitivo')], max_length=20)),
                ('condicion', models.CharField(blank=True, choices=[('PRESUNTIVO', 'Presuntivo'), ('DEFINITIVO_INICIAL', 'Definitivo inicial'), ('DEFINITIVO_CONFIRMADO_LAB', 'Definitivo confirmado lab'), ('DEFINITIVO_CONTROL', 'Definitivo control')], max_length=30, null=True)),
                ('cronologia', models.CharField(blank=True, choices=[('PRIMERA', 'Primera'), ('SUBSECUENTE', 'Subsecuente')], max_length=15, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion_cie10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id_cie10', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'cie10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_cita', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELECONSULTA', 'Teleconsulta'), ('DOMICILIO', 'Domicilio'), ('OTRO', 'Otro')], default='PRESENCIAL', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTE', 'No asiste'), ('REPROGRAMADA', 'Reprogramada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncuestaCita',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField()),
            ],
            options={
                'db_table': 'encuesta_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('frontal', models.TextField(blank=True, null=True)),
                ('posterior', models.TextField(blank=True, null=True)),
                ('general', models.TextField(blank=True, null=True)),
                ('neurologico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'examen_fisico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaCie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIO', 'Secundario'), ('PRESUNTIVO', 'Presuntivo'), ('DEFINITIVO', 'Definitivo')], max_length=20)),
                ('condicion', models.CharField(blank=True, choices=[('PRESUNTIVO', 'Presuntivo'), ('DEFINITIVO_INICIAL', 'Definitivo inicial'), ('DEFINITIVO_CONFIRMADO_LAB', 'Definitivo confirmado lab'), ('DEFINITIVO_CONTROL', 'Definitivo control')], max_length=30, null=True)),
                ('cronologia', models.CharField(blank=True, choices=[('PRIMERA', 'Primera'), ('SUBSECUENTE', 'Subsecuente')], max_length=15, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historia_cie10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_elaboracion', models.DateField()),
                ('expediente_no', models.CharField(max_length=50, unique=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo'), ('UNION_LIBRE', 'Unión libre'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=120, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=15)),
                ('alimentacion', models.TextField(blank=True, null=True)),
                ('higiene', models.TextField(blank=True, null=True)),
                ('inmunizaciones', models.TextField(blank=True, null=True)),
                ('quirurgicos', models.TextField(blank=True, null=True)),
                ('traumaticos', models.TextField(blank=True, null=True)),
                ('transfusionales', models.TextField(blank=True, null=True)),
                ('alergicos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historia_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioDoctor',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('medio', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido'), ('LEIDO', 'Leído')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionSistemas',
            fields=[
                ('id_revision', models.AutoField(primary_key=True, serialize=False)),
                ('organos_sentidos', models.TextField(blank=True, null=True)),
                ('respiratorio', models.TextField(blank=True, null=True)),
                ('cardiovascular', models.TextField(blank=True, null=True)),
                ('digestivo', models.TextField(blank=True, null=True)),
                ('genital', models.TextField(blank=True, null=True)),
                ('urinario', models.TextField(blank=True, null=True)),
                ('esqueletico', models.TextField(blank=True, null=True)),
                ('muscular', models.TextField(blank=True, null=True)),
                ('nervioso', models.TextField(blank=True, null=True)),
                ('endocrino', models.TextField(blank=True, null=True)),
                ('hemo_linfatico', models.TextField(blank=True, null=True)),
                ('tegumentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'revision_sistemas',
                'managed': False,
            },
        ),
    ]
