# Generated by Django 4.2.23 on 2025-10-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0004_archivoatencion_archivocita_atencion_atencioncie10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
    ]
