# Generated by Django 4.2.23 on 2025-10-07 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medessentia', '0005_alter_cita_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_doctor',
            field=models.ForeignKey(db_column='id_doctor', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='registrado_por',
            field=models.ForeignKey(db_column='registrado_por', default=5, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_registradas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADA', 'CONFIRMADA'), ('ATENDIDA', 'ATENDIDA'), ('CANCELADA', 'CANCELADA'), ('NO_ASISTE', 'NO_ASISTE'), ('REPROGRAMADA', 'REPROGRAMADA')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('TELECONSULTA', 'TELECONSULTA'), ('DOMICILIO', 'DOMICILIO'), ('OTRO', 'OTRO')], default='PRESENCIAL', max_length=20),
        ),
    ]
