# Generated by Django 4.2.23 on 2025-10-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0006_cita_id_doctor_cita_id_paciente_cita_registrado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariodoctor',
            options={'verbose_name': 'Horario Doctor', 'verbose_name_plural': 'Horarios Doctores'},
        ),
    ]
