# Generated by Django 4.2.23 on 2025-10-09 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medessentia', '0007_alter_horariodoctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodoctor',
            name='id_doctor',
            field=models.ForeignKey(db_column='id_doctor', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='horarios_doctor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='horariodoctor',
            constraint=models.UniqueConstraint(fields=('id_doctor', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_horario_doctor_dia_tramo'),
        ),
    ]
