# Generated by Django 4.2.24 on 2025-10-27 23:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Medessentia', '0008_horariodoctor_id_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoAtencion',
        ),
        migrations.DeleteModel(
            name='ArchivoCita',
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
        migrations.DeleteModel(
            name='AtencionCie10',
        ),
        migrations.DeleteModel(
            name='EncuestaCita',
        ),
        migrations.DeleteModel(
            name='ExamenFisico',
        ),
        migrations.DeleteModel(
            name='HistoriaCie10',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='RevisionSistemas',
        ),
        migrations.AlterModelOptions(
            name='horariodoctor',
            options={},
        ),
        #migrations.RemoveConstraint(
           # model_name='horariodoctor',
            #name='uq_horario_doctor_dia_tramo',
        #),
        migrations.AddField(
            model_name='cita',
            name='id_horario',
            field=models.ForeignKey(blank=True, db_column='id_horario', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='Medessentia.horariodoctor'),
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='es_recurrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2025, 10, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2025, 10, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariodoctor',
            name='tipo_horario',
            field=models.CharField(choices=[('TRABAJO', 'Trabajo'), ('ALMUERZO', 'Almuerzo'), ('DESCANSO', 'Descanso')], default='TRABAJO', max_length=20),
        ),
        migrations.AlterField(
            model_name='horariodoctor',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='horariodoctor',
            name='id_doctor',
            field=models.ForeignKey(db_column='id_doctor', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
