# Generated by Django 4.2.24 on 2025-10-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0009_delete_archivoatencion_delete_archivocita_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horariodoctor',
            name='uq_horario_doctor_dia_tramo',
        ),
    ]
