# Generated by Django 4.2.24 on 2025-11-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medessentia', '0010_remove_horariodoctor_uq_horario_doctor_dia_tramo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cie10',
            options={'managed': False, 'verbose_name': 'CIE-10', 'verbose_name_plural': 'Códigos CIE-10'},
        ),
    ]
